#include <iostream>
#include "DFS.h"
#include "Perfect_Maze.h"
// #include "backtrace.h"
using namespace std;

int main() {
    //signal(SIGSEGV, signal_handler);

    int row, column;
    cin >> row >> column;
    Maze M(row, column);
    DFS dfs;
    // dfs.generate(M);
    // cout << "--------------------Maze generated by DFS--------------------" << endl;
    // M.print_node_all();

    // M.reset();
    // M.print_node_all();

    Perfect_Maze P;
    P.generate(M);
    cout << "--------------------Maze generated by PM--------------------" << endl;
    M.print_node_all();

    cout << "--------------------Maze solved by DFS----------------------" << endl;
    dfs.solve(M);

    //在终端输出带颜色的路径 最后可以尝试在终端复现寻路过程(利用光标定位)
    //dfs.print_results(M);
    return 0;
}